spring: 
  application: 
    name: "angersapp"
  datasource: 
    url: "jdbc:mysql://localhost:3306/mydb"
    username: "anger"
    password: "anger"
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081